#!/usr/bin/env python3

import sys
import subprocess
           
def checkModeExistsCrt(videomode):
    # specific resolution given
    proc = subprocess.Popen(["batocera-resolution listModesSys"], stdout=subprocess.PIPE, shell=True)
    (out, err) = proc.communicate()
    for valmod in out.decode().splitlines():
        vals = valmod.split(":")
        if(videomode == vals[0]):
            print("y")
            return True


mode= sys.argv[1]
checkModeExistsCrt(mode)
